sudo: required

services:
  - docker

before_install:
  - docker build ./client -t mainakmaitra/react-test -f ./client/Dockerfile.dev

script:
  - docker run -e CI=true mainakmaitra/react-test npm run coverage

after_success:
  - docker build -t mainakmaitra/multi-client ./client
  - docker build -t mainakmaitra/multi-server ./server
  - docker build -t mainakmaitra/multi-nginx ./nginx -f ./nginx/Dockerfile.dev
  - docker build -t mainakmaitra/multi-worker ./worker
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  - docker push mainakmaitra/multi-client
  - docker push mainakmaitra/multi-server
  - docker push mainakmaitra/multi-nginx
  - docker push mainakmaitra/multi-worker 

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-026502654526"
  bucket_path: "multi-docker"
  on:
      branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
      secure: "$AWS_SECRET_KEY"